import Header from "./components/Header";
import ProjectCard from "./components/ProjectCard";
import { experiences, profile, projects, skills } from "./data/portfolio";

const Arrow = () => <span aria-hidden="true">↗</span>;

export default function App() {
  return <><a className="skip-link" href="#main">Skip to content</a><Header /><main id="main">
    <section className="hero container" id="top"><p className="eyebrow"><span></span> Available for work</p><div className="hero-grid"><div><p className="kicker">FULL-STACK DEVELOPER · KADUNA, NIGERIA</p><h1>Websites and web applications built to solve real-world problems.</h1><p className="hero-copy">I’m {profile.name}, a full-stack developer building practical web experiences, secure APIs, databases, and dependable deployment.</p><div className="hero-actions"><a className="button button-primary" href="#work">View projects</a><a className="button button-secondary" href="#contact">Start a conversation</a></div></div><aside className="availability-card" aria-label="Professional summary"><p className="card-label">EXPERIENCE</p><p>Full-stack and web development since September 2024.</p><div className="availability-rule"></div><p className="card-label">OPEN TO</p><ul><li>Websites and web applications</li><li>Frontend and backend development</li><li>Available for work</li></ul></aside></div></section>
    <section className="section section-muted" id="about"><div className="container split-section"><div><p className="section-index">01 / ABOUT</p><h2>Reliable development, from first idea to live product.</h2></div><div className="prose"><p>I work across the full web-development lifecycle: shaping a clear interface, building backend functionality, designing data flows, integrating services, and deploying the finished product.</p><p>My approach is straightforward: understand the business need, choose practical technology, and deliver software that is easy to use and maintain.</p><dl className="facts"><div><dt>Location</dt><dd>{profile.location}</dd></div><div><dt>Role</dt><dd>Full-Stack Developer</dd></div><div><dt>Primary stack</dt><dd>JavaScript, Node.js, PostgreSQL</dd></div></dl></div></div></section>
    <section className="section" id="experience"><div className="container"><div className="section-heading"><div><p className="section-index">02 / EXPERIENCE</p><h2>Building websites and web applications since September 2024.</h2></div><p>Professional full-stack and web development focused on practical, real-world problems.</p></div><div className="experience-list">{experiences.map((experience) => <article className="experience-card" key={experience.title}><p className="project-type">{experience.period}</p><div><h3>{experience.title}</h3><p>{experience.link ? <>Maintenance work for <a className="text-link" href={experience.link} target="_blank" rel="noopener">malekanaturals.com <Arrow /></a>.</> : experience.description}</p>{experience.points && <ul className="project-points">{experience.points.map((point) => <li key={point}>{point}</li>)}</ul>}</div></article>)}</div></div></section>
    <section className="section section-muted" id="work"><div className="container"><div className="section-heading"><div><p className="section-index">03 / SELECTED PROJECTS</p><h2>Connected business systems and interactive frontend work.</h2></div><p>Jai’fore and A&amp;M Infinity Bites each include a customer platform and administrative layer.</p></div><div className="project-list">{projects.map((project) => <ProjectCard project={project} key={project.number} />)}</div></div></section>
    <section className="section section-muted" id="skills"><div className="container"><div className="section-heading"><div><p className="section-index">04 / SKILLS</p><h2>Technology used across verified work.</h2></div></div><div className="skills-grid">{skills.map(([title, content]) => <article key={title}><h3>{title}</h3><p>{content}</p></article>)}</div></div></section>
    <section className="section approach-section" aria-labelledby="approach-title"><div className="container split-section"><div><p className="section-index">05 / APPROACH</p><h2 id="approach-title">Practical development for the whole product.</h2></div><div className="approach-list"><article><span>01</span><p>Clear, responsive interfaces for the people using the product.</p></article><article><span>02</span><p>Backend functionality, data flows, and integrations that support the experience.</p></article><article><span>03</span><p>Deployment-minded delivery that keeps the finished product maintainable.</p></article></div></div></section>
    <section className="section contact-section" id="contact"><div className="container contact-layout"><div><p className="section-index">06 / CONTACT</p><h2>Let’s talk about the work.</h2><p>Available for work · {profile.location}</p></div><div className="contact-actions"><a href={`mailto:${profile.email}`}>{profile.email} <Arrow /></a><a href="https://github.com/movffasea-byte" target="_blank" rel="noopener">github.com/movffasea-byte <Arrow /></a><a href="https://www.linkedin.com/in/jaifore-abraham-gaba" target="_blank" rel="noopener">linkedin.com/in/jaifore-abraham-gaba <Arrow /></a></div></div></section>
  </main><footer className="footer"><div className="container footer-content"><span className="footer-mark" aria-hidden="true">G</span><p>© {new Date().getFullYear()} {profile.name} · {profile.brand} · {profile.location}.</p></div></footer></>;
}
